/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_sampleaubio_TempoDetector */

#ifndef _Included_com_example_sampleaubio_TempoDetector
#define _Included_com_example_sampleaubio_TempoDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_sampleaubio_TempoDetector
 * Method:    detectTempo
 * Signature: (Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_example_sampleaubio_TempoDetector_detectTempo
  (JNIEnv *, jclass, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
