package org.skplanetx.openapi.tmap;

public class PoiDetailInfo {
	public String id;
	public String name;
	public String bizCatName;
	public String address;
	public String firstNo;
	public String secondNo;
	public String zipCode;
	public String tel;
	public String lat;
	public String lon;
	public String menu1;
	public String menu2;
	public String menu3;
	public String menu4;
	public String menu5;
	public int parkFlag;
	public String twFlag;
	public String yaFlag;
	public String homepageURL;
	public String routeInfo;
	public String facility;
	public String upperLegalCode;
	public String middleLegalCode;
	public String lowerLegalCode;
	public String detailLegalCode;
	public String upperAdminCode;
	public String middleAdminCode;
	public String lowerAdminCode;
	public String upperCode;
	public String middleCode;
	public String lowerCode;
	public int participant;
	public int point;
	public String merchantFlag;
	public String merchantDispType;
	public String addionalInfo;
}
